general:
  download: True | False
  image editing: True | False
  log file path: <path/to/log/file.log>
  update frequency: daily | weekly | bi-weekly | 1d (for 1 day) | 1h (for 1 hour) | etc
interface:
  api:
    google search api key: <Google API key>
    imdb custom search id: <Custom IMDb search engine ID>
